FROM library/python:3.8.5

RUN mkdir -p /app
WORKDIR /app

COPY ./requirements.txt /app
RUN pip install -r requirements.txt

COPY . /app

EXPOSE 80
COPY ./runserver.sh /usr/local/bin/
CMD [\"sh\", \"runserver.sh\"]